import Link from "next/link";
import { ArrowRight, BrainCircuit, Users, LockKeyhole, Check } from "lucide-react";
import { APP_TAGLINE } from "@/lib/constants/app";

function MiniBoard(): React.ReactElement { return <div className="mini-board" aria-label="Demonstração de um tabuleiro com cinco peças alinhadas">{Array.from({ length: 81 }, (_, index) => <span className={[30, 40, 50, 60, 70].includes(index) ? "mini-piece dark" : [31, 41, 51, 61].includes(index) ? "mini-piece light" : ""} key={index} />)}</div>; }

export default function HomePage() {
  return <div className="landing"><section className="hero"><div className="hero-copy"><p className="eyebrow">Estratégia em cada jogada</p><h1>{APP_TAGLINE}</h1><p className="hero-lede">Um clássico de estratégia, redesenhado para partidas rápidas no seu ritmo. Comece contra a IA — sem conta.</p><div className="action-row"><Link className="button primary" href="/jogar">Jogar agora <ArrowRight size={18} /></Link><Link className="button secondary" href="/como-jogar">Como jogar</Link></div><p className="hint"><Check size={16} /> Sem cadastro para jogar contra a IA</p></div><div className="hero-board"><MiniBoard /><div className="board-caption"><BrainCircuit size={18} /> IA com 3 níveis de desafio</div></div></section><section className="steps"><p className="eyebrow">Comece em segundos</p><h2>Uma regra. Muitas possibilidades.</h2><div className="step-grid"><article><span>01</span><h3>Escolha seu modo</h3><p>Treine contra a IA ou entre para desafiar outras pessoas.</p></article><article><span>02</span><h3>Posicione sua peça</h3><p>Construa suas linhas e interrompa os planos do adversário.</p></article><article><span>03</span><h3>Alinhe cinco</h3><p>Vence quem formar uma linha contínua antes.</p></article></div></section><section className="mode-grid"><article><BrainCircuit /><h3>Contra IA</h3><p>Três dificuldades para aprender, treinar e evoluir.</p><Link href="/jogar/ia">Treinar agora →</Link></article><article><Users /><h3>Partida casual</h3><p>Encontre um adversário para uma partida sem ranking.</p><Link href="/multiplayer">Ir ao multiplayer →</Link></article><article><LockKeyhole /><h3>Sala privada</h3><p>Crie um código e desafie alguém que você conhece.</p><Link href="/multiplayer/criar">Criar sala →</Link></article></section><section className="account-callout"><div><p className="eyebrow">Quando quiser competir</p><h2>Crie uma conta gratuita.</h2><p>Salve seu histórico e jogue partidas online em tempo real.</p></div><Link className="button primary" href="/cadastrar">Criar conta</Link></section></div>;
}
